services:
  database:
    image: postgres:16-alpine
    container_name: task_manager_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_db
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
